import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { ConvexClientProvider } from "@/providers/convex-client-provider";
// import { ConvexClientProvider } from "@/providers/convex-client-provider";
// import { AuthLoading,Authenticated } from "convex/react";
// import Loading from '@/components/loading/loading'
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/providers/modal-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      // <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster />
          <ModalProvider/>
      <SignedOut> 
        <SignInButton />
        </SignedOut> 
        <SignedIn>
          {/* <UserButton /> */}
        </SignedIn>
        {/* <Authenticated> */}
          {children}
        {/* </Authenticated> */}
        {/* <AuthLoading> */}
          {/* <Loading/cd > */}
        {/* </AuthLoading> */}
        </ConvexClientProvider>
        </body>
    </html>
        // </ClerkProvider>
  );
}
